# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Las Vegas Suzuki Music
email: lvdesertsuzuki@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Las Vegas Suzuki music institute. We welcome all students of Flute, Piano, Violin and Viola as well as teachers seeking to obtain Suzuki book registration.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lvdesertsuzuki.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
google_analytics: "UA-113941522-1"
flute_reg_url: "/registration/flute-piano.html"
piano_reg_url: "/registration/flute-piano.html"
violin_reg_url: "#"
intro_reg_url: "/registration/intro.html"
bg_fv_reg_url: "#"
donate_url: "/cart.html#!/Donations/c/12752637/offset=0&sort=normal"
year: "2019"
next_year: "2020"

# Tuition rates
tui_intro: 50
tui_beg_flute_violin: 75
tui_flute_books1_2: 300
tui_flute_books3_4: 395
tui_flute_adv: 485
tui_piano_books1_2: 300
tui_piano_books3_4: 395
tui_violin_books1_2: 300
tui_violin_books3_4: 395
tui_enrichment_add: 70 

# Registration fees
reg_1: 75
reg_2: 85
reg_3: 95
reg_sibling_discount: 15

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
   - .git/
   - README.md
   - .DS_Store